### ISSUE TITLE
[Bug] Flag CF After executing SHR

### ISSUE THREAD

**Issue by Narukara** [YJDoc2/8086-emulator-web#17]
I am not sure if this is a bug since I am an 8086 beginner.

I am using the 8086 emulator on the web page and I found a problem:

When I execute:

```assembly
start:
MOV CX, 0x0004
MOV DX, 0x0010
SHR DX, CL
```

Finally CF will be set to 1.

And when I execute:

```assembly
start:
MOV CX, 0x0004
MOV DX, 0x000F
SHR DX, CL
```

Finally CF will be set to 0.

I believe this violates the definition of the SHR instruction.

**Comment by YJDoc2** [comment]
Hey I have updated the core lib, as well as the dependency in this repo. Now this should give the results as expected. Please check once, and if fine, close the issue.
Thanks for reporting!
