### ISSUE TITLE
Can't use Registers Name in Macros Parameters

### ISSUE THREAD

**Issue by FrancoisCapon** [YJDoc2/8086-emulator-web#20]
Hi,

I think that because the parameter `AX`  (for example) is not treated as a string in a macro parameter but is first recognized as a register:
```asm
MACRO reset(register) -> MOV register, 0x0000 <-
start:
reset(AX) ; AX "colored"
Errors:
Syntax Error at line 3:4 : reset(AX) : Unexpected Token : AX  <- no macro expansion
```
```asm
MACRO reset(register) -> MOV register, 0x0000 <-
start:
reset(AZ) ; AZ not "colored"
Errors:
Syntax Error at 3:0 : reset(AZ) : Error in Macro Expansion :   <- macro expansion is done
Expanded Macro : MOV AZ, 0x0000 Error: Unexpected Token AZ
```
I tried to "set the type", but It doesn't  work.
```asm
MACRO reset(register) -> MOV register, 0x0000 <-
start:
reset('AX')
Syntax Error : Invalid token at 58
```
```asm
MACRO reset(register) -> MOV register, 0x0000 <-
start:
reset("AX")
Errors:
Syntax Error at line 3:4 : reset("AX") : Unexpected Token : "AX"
```

Thanks for this very pedagogic emulator :+1:

**Comment by YJDoc2** [comment]
Hey, Thanks for reporting :+1:

This is definitely an important error, as this severely limits the usefulness of macros. Ideally the first example you gave should work.

I feel that this happens because the way parser is defined, and the way the library we use to generate parser works :
The library parses the token using the order of their definition as precedence. As the strings for macro params are defined after registers, the registers take precedence, and these are parsed as registers and not as  macro params.

I will try to fix this soon.

Hope you are finding the emulator useful, and thanks again for reporting :)

>Thanks for this very pedagogic emulator :+1:

:) :) :)

**Comment by YJDoc2** [comment]
Hey I have made a patch that should fix this as much as it can :
The first example of code works now, with registers passing as valid macro params, similarly you can pass other macros, registers and even simple memory address as params.

Still this does not allow passing segement overridden memory address (byte es [5]) or memory address with offset (word [5,7]) or instruction or part of an instruction as a param.
So macro_call(mov ax) will fail. Similarly you cannot use half instrcutions in macro body as well :
```
Macro mac (a) -> a(_) AX,BX <- 
mac(ADD)

```
is still invalid.

This is already pushing the boundaries of parser library this uses, and to solve any of the above issue, the only solution I can think of right now is to write a custom parser, which this might need someday, but right now will be too much of work. So the macros will have to work with these restrictions.

That said, the issue you reported is now solved, and you can use registers as macro params. (you might need to hard refresh (ctrl+f5) in browser is using the cached pages)

Please check once and let know if any other error or issue regarding this, or else feel free to close this issue.

Thanks for reporting :)

**Comment by FrancoisCapon** [comment]
> Macros will therefore have to work with these restrictions.

 It's  widely  sufficient, thanks.  :+1: 
I close the issue.
