### ISSUE TITLE
How can I make a web page as good-looking as yours?

### ISSUE THREAD

**Issue by sanbuphy** [YJDoc2/8086-emulator-web#31]
I think your web page is very cool! Is there any way I can also make a homepage like this? Thank you very much

**Comment by YatharthVyas** [comment]
Thank you for appreciating our website design!

We made use of https://mui.com/ to style all our components. We decided to be minimalistic but you can play around and get creative with the tools. Another clever trick to use here is a custom theme with a color pallet and font style that reflects the theme of your website.

Good Luck building :)

**Comment by sanbuphy** [comment]
> Thank you for appreciating our website design!
> 
> We made use of https://mui.com/ to style all our components. We decided to be minimalistic but you can play around and get creative with the tools. Another clever trick to use here is a custom theme with a color pallet and font style that reflects the theme of your website.
> 
> Good Luck building :)

Get it !  Thank you for your reply, have a nice day.
